travis:
  secure:
    BINSTAR_TOKEN: M0fI/2PgcNBSkB6YoN9VvG/NGpwTn1YPGTt5TOg5CTAsMnRmENfBLK6nOD6Qym/pQDBeWpKzB97FENF9LXBeMZSiLG9sWxTEsbqx0KR2S/wGVdSzjp+G9PzsZRbE3NKj/1XwFNgUvFy+PZdeEAhlI2qV4ogxb4asbjfOUM1ZNp7MnUaF25+zztY4WlIzpXTUVDwivpnnxkBy3THvSSHuzlNwCPpmXuPrzENfWRAGmTH7/N2cuoTai51fJCkR7P5yvfckkjCdnqBZxuykJvFVg5bVL2gQt0myoBYgR6Jqx+X2fXuhnGMgi/N9VLyL5b54ducxw6f30Lpf5hzuiULTYytCE72f4flDTQm/HaV5TovNRnOSVxYJZBTTIBtnWgQ4B786RAgNdFI851FiGc0GubEp4jBWFFVjMbhT520g7JPbOPpr0hdI3CpJeZGzSvCAp7aDb89jPsPIu+2O6x8O7p1Sc4WziDFWYoc5+1/pzrfq0apbHO55kvWIGThfLmB5AaI7lE7Thf08oaR3ePxkvZUKwTJWt9TnLVtdjb8qXVNgqogUWzGOq5X+wO+u31xLf5aPrZJbOglw23pIXqGRySUT+gUGhAiWB8NG1Wat88S4atbjJQ14ipJplFKn1ZYP5QhusmFSLrXyB53Bxzzqfm93JCt4SfTBRdo19rJ48oY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
