travis:
  secure:
    BINSTAR_TOKEN: nR59C3Nn8OZzNi/7sDzv0cPUdbhSJMpJQepSD+LwrADU9zaSOuETy7q4CHWrzhuCB909K0tWk8papWbPoX5L+PMavlBIZgfAv5Qa6rUem0UaRasHMokGLkCTXg+eyNat5MEVC2+vbkGNeFZMXyaIgmxI4bDqco9+2p4+JXigu82WpIqLzaVQ9JEJ2dV+aNUL56c95BXiTlnl+OjYmQOGl6rMUhBTkKELJdaTRG3pxFY13qDql0WvthcYI2kPIHBWBchEQLhL5nD2go3KA7tG7sNXKz3ozA5srqYcBL9lBWD1NHiINLLCHWptOm8fb68z/4SCrAVvimGBFz1uq4rQZjrh0y+kP6QGn5aYoWo+RFbXZyz+vHWd1gbK75q75d3ySQNNgiEOUQ1nn4s1sSU68F2ekv6BNE43d0nMmR+vOKebsX7tFAdWIe4jsXWAhSTm4FXnhTq8jsSAXVfqUAz6OujApj3kXJ1i517NTogjif5ZscoBANEyWSAox+HXOXGyU0bfBbhyduFgwab2Cei3eyV6+gSK/IBvCdZcUM+ZUNGnwjNNK7dtZjWJtZQIyZKfP+UvIL6riLOGojhhMK6Rvs0zM1NYRMYA73v9M4lm5EeoGC6csNJZx0zf2zlXfHIpG/kIJUqzq2Bk/GU7ISBDWGe6GnwqKzDXsG1UTBxtVns=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
